name: build-on-push

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install fyne package
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Install go1.19
        run: go install golang.org/dl/go1.19.13@latest
      #- name: Download go1.19
      #  run: go1.19.13 download
      #- name: Add go1.19 to the PATH
      #   run: echo "export GOPHERJS_GOROOT=\"$(go1.19.13 env GOROOT)\"" >> ~/.bashrc
      - name: Install gopherjs
        run: go install github.com/gopherjs/gopherjs@v1.19.0-beta1
      - name: Install just
        run: apt install just
      - name: Build
        run: just build-js
